#!/usr/bin/env python3

import argparse

from splitbill import SplitBill

if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    parser.add_argument('-o',
            help='output csv file',
            dest='output',)

    parser.add_argument('files',
            help='csv file(s) to process',
            nargs='*',)

    args = parser.parse_args()

    # splitbill
    sb = SplitBill()
    csv = sb.open(args.files)
    result = sb.calculate(csv)

    # output
    if args.output:
        sb.format_csv(result, args.output)
        exit()

    sb.format_stdout(result)
