#!/usr/bin/env python3

import argparse
import fileinput
import re

if __name__ == '__main__':
    paid = {}; received = {};

    with fileinput.input() as file:
        for f in file:
            # ignore comments
            row = re.sub(r'#.*', '', f)

            # remove trailing newline to match awk functionality
            row = [f for f in re.sub(r'\n$', '', f).split(',')]

            if len(row) < 4:
                continue

            try:
                vpaid = float(row[2])
            except ValueError:
                continue

            paid[row[0]] = paid.setdefault(row[0], 0) + vpaid
            received.setdefault(row[0], 0)

            for p in row[3:]:
                received[p] = received.setdefault(p, 0) + vpaid / len(row[3:])
                paid.setdefault(p, 0)

    lent = {p:paid[p] - received[p] for p in paid.keys()}

    for p in sorted(lent.keys()):
        print('{}\t\t{:.2f}'.format(p, lent[p]))
